[package]
name = "nebula_task"
version = "0.1.0"
authors = ["Dongdong Zhou <dz@yay.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0.1", features = ["full"]}
rayon = "1.10.0"
anyhow = "1.0.34"
crossbeam = "0.8.0"
lazy_static = "1.4.0"
num_cpus = "1.13.0"